---
- name: Find service name
  set_fact:
    service_name: '{{service|default(meta.name+"-rabbitmq")}}'

- name: Find configMap name
  set_fact:
    configmap_name: '{{configmap|default(meta.name+"-rabbitmq")}}'

- import_tasks: rbac.yml

- import_tasks: secret.yml

- import_tasks: configmap.yml

- import_tasks: service.yml

- import_tasks: sts.yml

- import_tasks: users.yml
