---

- name: Find service name
  set_fact:
  service_name: |-
    {% if service is defined %}
    '{{ meta.name }}-rabbitmq-service'
    {% else %}
    {{ service }}
    {% endif %}


- name: Find configMap name
  set_fact:
  configMap_name: |-
    {% if configMap is defined %}
    '{{ meta.name }}-rabbitmq-configMap'
    {% else %}
    {{ configMap }}
    {% endif %}

- import_tasks: rbac.yml

- import_tasks: secret.yml

- import_tasks: configmap.yml

- import_tasks: service.yml

- import_tasks: sts.yml
