---
- name: Add ServiceAccount
  k8s:
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: '{{ meta.name }}-rabbitmq'
        namespace: '{{ meta.namespace }}'

- name: Add rbac
  k8s:
    definition:
      kind: Role
      apiVersion: rbac.authorization.k8s.io/v1beta1
      metadata:
        name: endpoint-reader
        namespace: '{{ meta.namespace }}'
      rules:
      - apiGroups: [""]
        resources: ["endpoints"]
        verbs: ["get"]

- name: Add rolebinding
  k8s:
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1beta1
      metadata:
        name: endpoint-reader
        namespace: '{{ meta.namespace }}'
      subjects:
      - kind: ServiceAccount
        name: '{{ meta.name }}-rabbitmq'
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: endpoint-reader


