---
- name: List Secrets
  k8s_facts:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    field_selectors: 'metadata.name={{ meta.name }}-rabbitmq'
  register: secret_list

- name: Add Erlang cookie secret
  k8s:
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        namespace: '{{ meta.namespace }}'
        name: '{{ meta.name }}-rabbitmq'
      type: Opaque
      data:
        RABBITMQ_ERLANG_COOKIE: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=250') | b64encode }}"
        RABBITMQ_DEFAULT_USER: '{{ "rabbit" | b64encode }}'
        RABBITMQ_DEFAULT_PASSWORD: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=250') | b64encode }}"
        
  when: not secret_list.resources|length>0
