---
- name: List Secrets
  k8s_facts:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    field_selectors: 'metadata.name={{ meta.name }}-rabbitmq'
  register: secret_list

- name: Add Secret
  k8s:
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        namespace: '{{ meta.namespace }}'
        name: '{{ meta.name }}-rabbitmq'
      type: Opaque
      data:
        token: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=250') | b64encode }}"
  when: not secret_list.resources|length>0
