---
- name: Add service
  k8s:
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        namespace: '{{ meta.namespace }}'
        name: '{{ service_name }}'
        labels:
          app: rabbitmq
          type: LoadBalancer
      spec:
        type: ClusterIP
        ports:
         - name: http
           protocol: TCP
           port: 15672
           targetPort: 15672
         - name: amqp
           protocol: TCP
           port: 5672
           targetPort: 5672
        selector:
          app: rabbitmq
  when: service is not defined
