---
- name: Add sts
  k8s:
    definition:
      apiVersion: apps/v1beta1
      kind: StatefulSet
      metadata:
        name: '{{ meta.name }}-rabbitmq'
        namespace: '{{ meta.namespace }}'
      spec:
        serviceName: '{{ service_name }}'
        replicas: "{{ size }}"
        template:
          metadata:
            labels:
              app: rabbitmq
              origincrd: '{{ meta.name }}'
          spec:
            serviceAccountName: '{{ meta.name }}-rabbitmq'
            terminationGracePeriodSeconds: 10
            initContainers:
            - name: bootstrap-configuration
              image: busybox
              command: ['/bin/sh', '-c', 'cp /etc/rabbitmq/files/* /etc/rabbitmq/']
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/rabbitmq/files
                - name: config
                  mountPath: /etc/rabbitmq
            containers:
            - name: rabbitmq-k8s
              image: rabbitmq:3.7
              volumeMounts:
                - name: config
                  mountPath: /etc/rabbitmq
              ports:
                - name: http
                  protocol: TCP
                  containerPort: 15672
                - name: amqp
                  protocol: TCP
                  containerPort: 5672
              livenessProbe:
                exec:
                  command: ["rabbitmqctl", "status"]
                initialDelaySeconds: 60
                # See https://www.rabbitmq.com/monitoring.html for monitoring frequency recommendations.
                periodSeconds: 60
                timeoutSeconds: 15
              readinessProbe:
                exec:
                  command: ["rabbitmqctl", "status"]
                initialDelaySeconds: 20
                periodSeconds: 60
                timeoutSeconds: 10
              imagePullPolicy: Always
              env:
                - name: MY_POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: RABBITMQ_USE_LONGNAME
                  value: "true"
                # See a note on cluster_formation.k8s.address_type in the config file section
                - name: RABBITMQ_NODENAME
                  value: "rabbit@$(MY_POD_IP)"
                - name: K8S_SERVICE_NAME
                  value: '{{ service_name }}'
              envFrom:
                - secretRef: 
                    name: '{{ meta.name }}-rabbitmq'
            volumes:
              - name: config
                emptyDir: {}
              - name: config-volume
                configMap:
                  name: '{{ configmap_name }}'
                  items:
                  - key: rabbitmq.conf
                    path: rabbitmq.conf
                  - key: enabled_plugins
                    path: enabled_plugins
