apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqs.rabbitmq.lse.epita.fr
spec:
  group: rabbitmq.lse.epita.fr
  names:
    kind: Rabbitmq
    listKind: RabbitmqList
    plural: rabbitmqs
    singular: rabbitmq
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
