kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rabbitmq-operator
subjects:
- kind: ServiceAccount
  name: rabbitmq-operator
  namespace: rabbitmq-op
roleRef:
  kind: ClusterRole
  name: rabbitmq-operator
  apiGroup: rbac.authorization.k8s.io
